const claims=[
 {id:"CLM-001",name:"Maria Torres",type:"Auto collision",risk:"critical",action:"INVESTIGATE",reason:"Damage estimate mismatch and elevated fraud risk.",metrics:[["Document completeness","100%","ok"],["Damage vs estimate","52%","flag"],["Fraud risk","82%","flag"],["Coverage match","95%","ok"]]},
 {id:"CLM-003",name:"Robert Kim",type:"Auto theft",risk:"warning",action:"REQUEST DOCUMENTS",reason:"Documentation is incomplete and damage evidence is insufficient.",metrics:[["Document completeness","60%","flag"],["Damage vs estimate","0%","flag"],["Fraud risk","45%","ok"],["Coverage match","90%","ok"]]},
 {id:"CLM-005",name:"David Okafor",type:"Auto collision",risk:"critical",action:"INVESTIGATE",reason:"Damage mismatch and fraud score exceed configured thresholds.",metrics:[["Document completeness","85%","ok"],["Damage vs estimate","64%","flag"],["Fraud risk","58%","flag"],["Coverage match","92%","ok"]]}
];
const list=document.getElementById("claimList"),detail=document.getElementById("detail");
function renderList(){list.innerHTML=claims.map((c,i)=>`<div class="claim ${i===0?"selected":""}" data-id="${c.id}"><div class="claim-row"><span class="claim-id">${c.id}</span><span class="badge ${c.risk}">${c.risk.toUpperCase()}</span></div><div class="claim-name">${c.name} · ${c.type}</div></div>`).join("");document.querySelectorAll(".claim").forEach(x=>x.onclick=()=>{document.querySelectorAll(".claim").forEach(y=>y.classList.remove("selected"));x.classList.add("selected");show(x.dataset.id)})}
function show(id){const c=claims.find(x=>x.id===id);detail.innerHTML=`<div class="detail"><span class="eyebrow">CLAIM ${c.id}</span><h2>${c.name}</h2><div class="sub">${c.type} · AI-assisted triage evidence</div><div class="risk-box"><strong>${c.risk.toUpperCase()} RISK</strong><div>${c.reason}</div></div><div class="metrics-grid">${c.metrics.map(m=>`<div class="metric"><label>${m[0]}</label><b class="${m[2]==="flag"?"flag":""}">${m[1]}</b></div>`).join("")}</div><div class="decision"><span>Decision Agent recommendation</span><b style="display:block;margin-top:5px">${c.action}</b><small>Human adjuster review required before final action.</small></div></div>`}
renderList();show(claims[0].id);
document.getElementById("runBtn").onclick=()=>{const b=document.getElementById("runBtn");b.textContent="Triage running…";setTimeout(()=>{b.textContent="Triage complete";setTimeout(()=>b.textContent="Run triage",1200)},900)};